
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"
import { type ProductType } from "./definitions";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const productTypeLabels: Record<ProductType, string> = {
  ART_OPEN_A1: "Artículo A1 (Acceso Abierto)",
  ART_A1: "Artículo A1",
  ART_OPEN_A2: "Artículo A2 (Acceso Abierto)",
  ART_A2: "Artículo A2",
  LIB_A1: "Libro A1",
  LIB_A: "Libro A",
  CAP_LIB_A1: "Capítulo de Libro A1",
  CAP_LIB_A: "Capítulo de Libro A",
  PA1: "Patente de Invención A1",
  PA2: "Patente de Invención A2",
  MA1: "Patente de Modelo de Utilidad A1",
  MA2: "Patente de Modelo de Utilidad A2",
  VV_A1: "Variedad Vegetal A1",
  VV_A2: "Variedad Vegetal A2",
  VA_A: "Nueva Raza Animal A",
  AAD_A1: "Producto de Creación/Investigación A1",
  AAD_A: "Producto de Creación/Investigación A",
  RNL_A: "Regulación/Norma A",
  ART_OPEN_B: "Artículo B (Acceso Abierto)",
  ART_B: "Artículo B",
  ART_OPEN_C: "Artículo C (Acceso Abierto)",
  ART_C: "Artículo C",
  LIB_B: "Libro B",
  CAP_LIB_B: "Capítulo de Libro B",
  PA3: "Patente de Invención A3",
  PA4: "Patente de Invención A4",
  MA3: "Patente de Modelo de Utilidad A3",
  MA4: "Patente de Modelo de Utilidad A4",
  VV_A3: "Variedad Vegetal A3",
  VV_A4: "Variedad Vegetal A4",
  VA_B: "Población Mejorada Pecuaria B",
  AAD_B: "Producto de Creación/Investigación B",
  DI_A: "Diseño Industrial A",
  ECI: "Esquema de Circuito Integrado",
  PP: "Planta Piloto",
  PI: "Prototipo Industrial",
  SD: "Signo Distintivo",
  SE: "Secreto Empresarial",
  FIS: "Solución de Interés Social",
  GPP_A: "Insumo de Política Pública A",
  GPP_B: "Insumo de Política Pública B",
  FCP_A: "Fortalecimiento de Cadena Productiva A",
  FCP_B: "Fortalecimiento de Cadena Productiva B",
  EC_A: "Evento Científico A",
  EC_B: "Evento Científico B",
  TC_A: "Taller de Creación A",
  TC_B: "Taller de Creación B",
  TC_C: "Taller de Creación C",
  NSG: "Nueva Secuencia Genética",
  ERL: "Edición de Revista/Libro",
  PCD_A1: "Producción de Contenido Digital A1",
  PCD_A2: "Producción de Contenido Digital A2",
};
